### ISSUE TITLE
[Suggestion] Start using vrp2_xxxxx as the resource's folder name

### ISSUE THREAD

**Issue by tabarra** [bradxy/vRP2-Scripts#1]
I think this is a great opportunity to introduce a tiny bit of versioning to the vrp general community.  
In this case, its quite important to make it clear this is not a `vrp / vrp old / vrpex / vrp 0.5 / vrp 1.0` compatible script.  
  
What do you guys think?

**Comment by jgabriel-soft** [comment]
Good ideia. It will give an organized start to vRP2!

**Comment by bradxy** [comment]
Theses scripts are only for vRP2, it says vrp2 in the title so someone should be able to tell the difference...
Also these scripts are just beta and I never meant to have issues opened on github... I will update the scripts and try to improve them over time...
