### ISSUE TITLE
addons_vrp

### ISSUE THREAD

**Issue by colormeblind23** [bradxy/vRP2-Scripts#3]
Not 100% sure but I think there is something causing the items to not work properly or maybe is conflicting with vrp built in items module but when you use smoke, the item required to be taken for the process to complete is not being taken from inventory. Way to reproduce is to attempt using a cigarette and watch to see if cigs is taken from inventory. Using latest build of vrp 2 on a dedicated server box. This issue did not occur till after updating addons_vrp2

**Comment by bradxy** [comment]
All the items are now defined in the add-ons server.lua. You need to remove all the items from within vRP so there no conflicts and let add-ons add the items. Check your server terminal for a Warning of conflicting items

**Comment by colormeblind23** [comment]
> All the items are now defined in the add-ons server.lua. You need to remove all the items from within vRP so there no conflicts and let add-ons add the items. Check your server terminal for a Warning of conflicting items

No, conflicting items. That issue was taken care of early on.

**Comment by bradxy** [comment]
try the new version and let me know if that resolves it thx!
